version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  image: latest
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
      # Force clean Sphinx build
      - rm -rf docs/_build

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
